DROP TABLE IF EXISTS posts_tags CASCADE;

DROP TABLE IF EXISTS tags CASCADE;

DROP TABLE IF EXISTS posts CASCADE;

DROP TABLE IF EXISTS post_types CASCADE;

DROP TABLE IF EXISTS follows CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS images CASCADE;

