version: "3.6"
name: mbsm
services:
  db:
    container_name: mbsm_db
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - mbsm
  redis:
    container_name: mbsm_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mbsm
  redis_http:
    container_name: mbsm_redis_http
    image: hiett/serverless-redis-http:latest
    ports:
      - "8079:80"
    depends_on:
      - redis
    environment:
      SRH_MODE: env
      SRH_TOKEN: "${UPSTASH_REDIS_REST_TOKEN}"
      SRH_CONNECTION_STRING: "redis://redis:6379"
    networks:
      - mbsm
  nginx:
    container_name: mbsm_nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/ssl/
    networks:
      - mbsm
networks:
  mbsm:
