version: "3.6"
name: mbsm
services:
  db:
    container_name: mbsm_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    networks:
      - mbsm
  redis:
    container_name: mbsm_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mbsm
  redis_http:
    container_name: mbsm_redis_http
    image: hiett/serverless-redis-http:latest
    ports:
      - "8079:80"
    depends_on:
      - redis
    environment:
      SRH_MODE: env
      SRH_TOKEN: "${KV_REST_API_TOKEN}"
      SRH_CONNECTION_STRING: "redis://redis:6379"
    networks:
      - mbsm
networks:
  mbsm:
