name: deploy

on:
  push:
    branches:
      - main
      - next

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print branch
        run: echo ${{ github.ref }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3.2.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_KEY_PASS }}
      - name: List keys
        run: gpg -K
