name: deploy

on:
  push:
    branches:
      - main
      - next

env:
  VERCEL_ENV: ${{  fromJSON('{"main":"production", "next":"preview"}')[github.ref_name] || ''  }}

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - name: Install Dependencies
        run: yarn install
      - name: Unlock Environment Variables
        uses: zemuldo/git-crypt-unlock@v2.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}
      - name: Set Environment Variables
        run: yarn env:${GITHUB_REF##*/}
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --scope snoozed --yes --environment=${{env.VERCEL_ENV}} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - name: Update Vercel Environment Variables
        run: yarn uploadEnvs --token=${{ secrets.VERCEL_TOKEN }}
