name: deploy

on:
  push:
    branches:
      - main
      - next

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print branch
        run: echo ${{ github.ref }}
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Cat local secrets
        run: cat env/.env.local
